import type { Metadata } from 'next';
import { DM_Sans, DM_Serif_Display, Belanosima } from 'next/font/google';
import './globals.css';

const dm_sans = DM_Sans({ subsets: ['latin'] });
const dm_serif_display = DM_Serif_Display({
	weight: '400',
	subsets: ['latin'],
});
const belanosima = Belanosima({
	weight: ['400', '600', '700'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${dm_sans.className} ${dm_serif_display.className} ${belanosima.className}`}
			>
				{children}
			</body>
		</html>
	);
}
